"""empty message

Revision ID: 0ad3e487a0ab
Revises: cf7960e7eca4
Create Date: 2021-11-03 23:18:47.255779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad3e487a0ab'
down_revision = 'cf7960e7eca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
