"""empty message

Revision ID: 340182b50a66
Revises: b70e5a05df9c
Create Date: 2021-11-06 15:15:53.036552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340182b50a66'
down_revision = 'b70e5a05df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
