"""token model

Revision ID: 4112396ac35b
Revises: c2619ba08c9b
Create Date: 2021-10-14 00:36:47.139334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4112396ac35b'
down_revision = 'c2619ba08c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
