"""empty message

Revision ID: a3d0c4085151
Revises: 340182b50a66
Create Date: 2021-11-08 23:49:38.973514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d0c4085151'
down_revision = '340182b50a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
