"""empty message

Revision ID: b70e5a05df9c
Revises: 0ad3e487a0ab
Create Date: 2021-11-06 12:13:48.010677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b70e5a05df9c'
down_revision = '0ad3e487a0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('jti', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('token', sa.Column('expire_at', sa.DateTime(), nullable=False))
    op.drop_index('ix_token_id', table_name='token')
    op.create_index(op.f('ix_token_expire_at'), 'token', ['expire_at'], unique=False)
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('token', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_token_expire_at'), table_name='token')
    op.create_index('ix_token_id', 'token', ['id'], unique=False)
    op.drop_column('token', 'expire_at')
    op.drop_column('token', 'jti')
    # ### end Alembic commands ###
