"""empty message

Revision ID: b7eb5b42bd40
Revises: 0bd4a5bc79f4
Create Date: 2021-11-16 11:42:26.082041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eb5b42bd40'
down_revision = '0bd4a5bc79f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('revoked', sa.Boolean()))
    op.drop_column('token', 'token_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('token_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('token', 'revoked')
    # ### end Alembic commands ###
